folio-org/ui-plugin-find-erm-usage-data-provider

- translations/ui-plugin-find-erm-usage-data-provider/ar.json
- translations/ui-plugin-find-erm-usage-data-provider/ca.json
- translations/ui-plugin-find-erm-usage-data-provider/da.json
- translations/ui-plugin-find-erm-usage-data-provider/de.json
- translations/ui-plugin-find-erm-usage-data-provider/en_GB.json
- translations/ui-plugin-find-erm-usage-data-provider/en_SE.json
- translations/ui-plugin-find-erm-usage-data-provider/en_US.json
- translations/ui-plugin-find-erm-usage-data-provider/es.json
- translations/ui-plugin-find-erm-usage-data-provider/es_ES.json
- translations/ui-plugin-find-erm-usage-data-provider/fr.json
- translations/ui-plugin-find-erm-usage-data-provider/fr_FR.json
- translations/ui-plugin-find-erm-usage-data-provider/hu.json
- translations/ui-plugin-find-erm-usage-data-provider/it_IT.json
- translations/ui-plugin-find-erm-usage-data-provider/pt_BR.json
- translations/ui-plugin-find-erm-usage-data-provider/pt_PT.json
- translations/ui-plugin-find-erm-usage-data-provider/zh_CN.json
> Update translation strings as of 20190225T222207

- translations/ui-plugin-find-erm-usage-data-provider/ar.json
- translations/ui-plugin-find-erm-usage-data-provider/pt_BR.json
> Update translation strings as of 20190227T140407

- translations/ui-plugin-find-erm-usage-data-provider/es_419.json
> Update translation strings as of 20190422T163602

- UDPSearch/UDPSearch.js
Noticed and fixed a few errors while adding support for adding a UDP to Agreements:
- Fixed prop-type errors
- Fixed aria-label prop
- Applied margin props to Button
> Fixes and applied margin props

- translations/ui-plugin-find-erm-usage-data-provider/zh_CN.json
> Update translation strings as of 20190729T163855

- translations/ui-plugin-find-erm-usage-data-provider/ru.json
- translations/ui-plugin-find-erm-usage-data-provider/zh_TW.json
> Update translation strings as of 20191014T135140

- translations/ui-plugin-find-erm-usage-data-provider/ja.json
> Update translation strings as of 20191028T205642

- translations/ui-plugin-find-erm-usage-data-provider/he.json
> Update translation strings as of 20191114T012425

- translations/ui-plugin-find-erm-usage-data-provider/fr_FR.json
> Update translation strings as of 20191122T140350

- translations/ui-plugin-find-erm-usage-data-provider/ur.json
> Update translation strings as of 20200210T220102

- translations/ui-plugin-find-erm-usage-data-provider/de.json
> Update translation strings as of 20200309T000645

- translations/ui-plugin-find-erm-usage-data-provider/ja.json
> Update translation strings as of 20200413T183215

- translations/ui-plugin-find-erm-usage-data-provider/ar.json
- translations/ui-plugin-find-erm-usage-data-provider/ca.json
- translations/ui-plugin-find-erm-usage-data-provider/da.json
- translations/ui-plugin-find-erm-usage-data-provider/de.json
- translations/ui-plugin-find-erm-usage-data-provider/en_GB.json
- translations/ui-plugin-find-erm-usage-data-provider/en_SE.json
- translations/ui-plugin-find-erm-usage-data-provider/en_US.json
- translations/ui-plugin-find-erm-usage-data-provider/es.json
- translations/ui-plugin-find-erm-usage-data-provider/es_419.json
- translations/ui-plugin-find-erm-usage-data-provider/es_ES.json
- translations/ui-plugin-find-erm-usage-data-provider/fr.json
- translations/ui-plugin-find-erm-usage-data-provider/fr_FR.json
- translations/ui-plugin-find-erm-usage-data-provider/he.json
- translations/ui-plugin-find-erm-usage-data-provider/hu.json
- translations/ui-plugin-find-erm-usage-data-provider/it_IT.json
- translations/ui-plugin-find-erm-usage-data-provider/ja.json
- translations/ui-plugin-find-erm-usage-data-provider/pt_BR.json
- translations/ui-plugin-find-erm-usage-data-provider/pt_PT.json
- translations/ui-plugin-find-erm-usage-data-provider/ru.json
- translations/ui-plugin-find-erm-usage-data-provider/ur.json
- translations/ui-plugin-find-erm-usage-data-provider/zh_CN.json
- translations/ui-plugin-find-erm-usage-data-provider/zh_TW.json
> Update translation strings as of 20200914T140557

- translations/ui-plugin-find-erm-usage-data-provider/ar.json
- translations/ui-plugin-find-erm-usage-data-provider/es.json
- translations/ui-plugin-find-erm-usage-data-provider/es_419.json
- translations/ui-plugin-find-erm-usage-data-provider/es_ES.json
- translations/ui-plugin-find-erm-usage-data-provider/fr_FR.json
- translations/ui-plugin-find-erm-usage-data-provider/hi_IN.json
- translations/ui-plugin-find-erm-usage-data-provider/ja.json
- translations/ui-plugin-find-erm-usage-data-provider/ko.json
> Update translation strings as of 20200921T192032

- translations/ui-plugin-find-erm-usage-data-provider/ja.json
- translations/ui-plugin-find-erm-usage-data-provider/pl.json
> Update translation strings as of 20200924T211627

- translations/ui-plugin-find-erm-usage-data-provider/zh_CN.json
> Update translation strings as of 20200928T202231

- translations/ui-plugin-find-erm-usage-data-provider/ber.json
> Update translation strings as of 20201109T135508

- translations/ui-plugin-find-erm-usage-data-provider/it_IT.json
> Update translation strings as of 20201111T142927

- package.json
- translations/ui-plugin-find-erm-usage-data-provider/en.json
https://issues.folio.org/browse/UIPFUDP-8
> UIPFUDP-8-upgrade-stripes-v6

- package.json
This PR adds @folio/stripes-cli v2 as a devDependency.
> UIPFUDP-12: Add stripes-cli v2 as devDep

- Jenkinsfile
- package.json
Refs. https://issues.folio.org/browse/UIPFUDP-13
> UIPFUDP-13: Compile Translation Files into AST Format 

- package.json
https://issues.folio.org/browse/UIPFUDP-15
> UIPFUDP-15: Increment stripes to v7

- CHANGELOG.md
- package.json
Also upgrade `stripes-acq-components` to `v4`
> UIPFUDP-27 Drop unneeded react-redux ref

- CHANGELOG.md
- src/UDPFilters.js
- src/UDPSearch.js
- src/UDPSearch.test.js
- src/UDPSearchContainer.js
- src/UDPSearchContainer.test.js
- src/UDPSearchModal.js
- src/UDPSearchModal.test.js
- src/UDPsView.js
- src/UDPsView.test.js
- test/jest/helpers/renderWithIntl.js
https://folio-org.atlassian.net/browse/UIPFUDP-35
> UIPFUDP-35: change class to function remove default props

- CHANGELOG.md
- package.json
- test/jest/__mock__/currencyData.mock.js
- test/jest/__mock__/index.js
- test/jest/__mock__/reactIntl.mock.js
- test/jest/__mock__/stripesConfig.mock.js
- test/jest/__mock__/stripesCore.mock.js
- test/jest/__mock__/stripesIcon.mock.js
https://folio-org.atlassian.net/browse/UIPFUDP-40
> UIPFUDP-40: Remove dependency to stripes-acq-components

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIPFUDP-42
Required by https://github.com/folio-org/mod-erm-usage/pull/185
> [UIPFUDP-42] Add support for interface aggregator-settings 2.0

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIPFUDP-43
See https://github.com/folio-org/mod-erm-usage-harvester/pull/182
> [UIPFUDP-43] Add support for interface erm-usage-harvester 2.0

- CHANGELOG.md
- src/UDPsView.js
https://folio-org.atlassian.net/browse/UIPFUDP-36
> UIPFUDP-36: Update results if deleting search string via keyboard
